---
# tasks file for valkyrie-elb
- apt:
    name: python-boto
- copy:
    src: /vagrant/boto.cfg
    dest: /etc/boto.cfg
    owner: root
    group: root
    mode: 0644
- local_action:
    module: ec2_elb_lb
    name: "create an ELB LB instance"
    state: present
#    zones:
#      - us-east-1a
    listeners:
      - protocol: http # options are http, https, ssl, tcp
        load_balancer_port: 80
        instance_port: 80
#      - protocol: https
#        load_balancer_port: 443
#        instance_protocol: http # optional, defaults to value of protocol setting
#        instance_port: 80
#        # ssl certificate required for https or ssl
#        ssl_certificate_id: "arn:aws:iam::123456789012:server-certificate/company/servercerts/ProdServerCert"
    health_check:
        ping_protocol: http # options are http, https, ssl, tcp
        ping_port: 80
        ping_path: "/index.html" # not required for tcp or ssl
        response_timeout: 5 # seconds
        interval: 30 # seconds
        unhealthy_threshold: 2
        healthy_threshold: 10
